handle:
  - rewrite: if (!is_dir() && !is_file()) goto "index.php?%{QUERY_STRING}"
  - rewrite: if (path ~ "sitemap.xml") goto "http://pwfee-wordpress.stor.sinaapp.com/sitemap.xml"
  - rewrite: if (path ~ "sitemap.html") goto "http://pwfee-wordpress.stor.sinaapp.com/sitemap.html"
